apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdimage-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: birdimage-api
  template:
    metadata:
      labels:
        app: birdimage-api
    spec:
      containers:
        - name: birdimage-api
          image: your-docker-registry/birdimage-api:latest
          ports:
            - containerPort: 4200
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.2"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: birdimage-api
spec:
  selector:
    app: birdimage-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
  type: LoadBalancer
