apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bird-app.fullname" . }}-api
  labels:
    {{- include "bird-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.birdApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "bird-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "bird-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: {{ .Chart.Name }}-api
          image: "{{ .Values.birdApi.image.repository }}:{{ .Values.birdApi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.birdApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.birdApi.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bird-app.fullname" . }}-api
  labels:
    {{- include "bird-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.birdApi.service.type }}
  ports:
    - port: {{ .Values.birdApi.service.port }}
      targetPort: {{ .Values.birdApi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "bird-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api