apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bird-app.fullname" . }}-bird-api
  labels:
    {{- include "bird-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: bird-api
spec:
  replicas: {{ .Values.birdApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "bird-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bird-api
  template:
    metadata:
      labels:
        {{- include "bird-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bird-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-bird-api
          image: "{{ .Values.birdApi.image.repository }}:{{ .Values.birdApi.image.tag }}"
          imagePullPolicy: {{ .Values.birdApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.birdApi.service.targetPort }}
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bird-app.fullname" . }}-birdimage-api
  labels:
    {{- include "bird-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: birdimage-api
spec:
  replicas: {{ .Values.birdImageApi.replicaCount }}
  selector:
    matchLabels:
      {{- include "bird-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: birdimage-api
  template:
    metadata:
      labels:
        {{- include "bird-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: birdimage-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-birdimage-api
          image: "{{ .Values.birdImageApi.image.repository }}:{{ .Values.birdImageApi.image.tag }}"
          imagePullPolicy: {{ .Values.birdImageApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.birdImageApi.service.targetPort }}
              protocol: TCP
