apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bird-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:VMLVaske/devops-challenge.git
    targetRevision: HEAD
    path: helm
    helm:
      values: |
        birdApi:
          image:
            tag: ${BIRD_API_TAG}
        birdImageApi:
          image:
            tag: ${BIRDIMAGE_API_TAG}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
