apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bird-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:VMLVaske/devops-challenge.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
