name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build Bird API
        working-directory: ./apis/bird
        run: |
          go mod tidy
          go build -v ./...

      - name: Test Bird API
        working-directory: ./apis/bird
        run: |
          go mod tidy
          go test -v ./...

      - name: Build BirdImage API
        run: |
          cd apis/birdImage
          go build -v ./...

      - name: Test BirdImage API
        run: |
          cd apis/birdImage
          go test -v ./...

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Bird API
        uses: docker/build-push-action@v6
        with:
          context: ./apis/bird
          file: ./apis/bird/Dockerfile.bird-api
          push: true
          tags: lilithvengeance/bird-api:${{ github.sha }}

      - name: Build and push BirdImage API
        uses: docker/build-push-action@v6
        with:
          context: ./apis/birdImage
          file: ./apis/birdImage/Dockerfile.birdimage-api
          push: true
          tags: lilithvengeance/birdimage-api:${{ github.sha }}

  update-helm-chart:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Helm chart values
        run: |
          sed -i 's|tag: .*|tag: "${{ github.sha }}"|' helm/values.yaml
          sed -i 's|tag: .*|tag: "${{ github.sha }}"|' helm/values.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add helm/values.yaml
          git commit -m "Update Helm chart image tags to ${{ github.sha }}"
          git push

  update-argocd:
    needs: update-helm-chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Get EC2 Private Key
        run: |
          PRIVATE_KEY=$(aws secretsmanager get-secret-value --secret-id k3s-private-key --query SecretString --output text)
          echo "$PRIVATE_KEY" > k3s_private_key.pem
          chmod 600 k3s_private_key.pem

      - name: Add EC2 instance to known hosts
        run: ssh-keyscan -H ${{ secrets.MASTER_IP }} >> ~/.ssh/known_hosts

      - name: Fetch kubeconfig from EC2 instance
        run: |
          ssh -i k3s_private_key.pem ubuntu@${{ secrets.MASTER_IP }} 'sudo cat /etc/rancher/k3s/k3s.yaml' > kubeconfig
          sed -i 's/127.0.0.1/${{ secrets.MASTER_IP }}/g' kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      - name: Update ArgoCD application
        run: |
          kubectl apply -f bird-app-infra/argocd/application.yaml
