name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build Bird API
        run: |
          cd apis/bird
          go mod tidy
          go build -v ./...

      - name: Test Bird API
        run: |
          cd apis/bird
          go mod tidy
          go test -v ./...

      - name: Build BirdImage API
        run: |
          cd apis/birdImage
          go build -v ./...

      - name: Test BirdImage API
        run: |
          cd apis/birdImage
          go test -v ./...

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Bird API
        uses: docker/build-push-action@v6
        with:
          context: ./apis/bird
          file: ./apis/bird/Dockerfile.bird-api
          push: true
          tags: lilithvengeance/bird-api:${{ github.sha }}

      - name: Build and push BirdImage API
        uses: docker/build-push-action@v6
        with:
          context: ./apis/birdImage
          file: ./apis/birdImage/Dockerfile.birdimage-api
          push: true
          tags: lilithvengeance/birdimage-api:${{ github.sha }}

  update-k8s-manifests:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Kubernetes manifests
        run: |
          sed -i 's|lilithvengeance/bird-api:.*|lilithvengeance/bird-api:${{ github.sha }}|' kubernetes/bird-api/deployment.yaml
          sed -i 's|lilithvengeance/birdimage-api:.*|lilithvengeance/birdimage-api:${{ github.sha }}|' kubernetes/birdimage-api/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add kubernetes/bird-api/deployment.yaml kubernetes/birdimage-api/deployment.yaml
          git commit -m "Update image tags to ${{ github.sha }}"
          git push
